# Generated by Django 4.2.7 on 2025-10-06 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('blog_image', models.ImageField(upload_to='images/blog/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('blog_author', models.CharField(blank=True, max_length=200, null=True)),
                ('first_paragraph', models.TextField()),
                ('middle_paragragh', models.TextField(blank=True, null=True)),
                ('final_paragragh', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=2, null=True)),
                ('blog_date', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, to='blog_categories.blogcategory')),
            ],
        ),
    ]
